POST http://localhost:5050/post-test HTTP/1.1
content-type: application/plain

Horse radish


###

POST http://localhost:5050/add?a=1&b=4 HTTP/1.1
content-type: application/plain

1+50

###

GET http://localhost:5050/add?a=1&b=4

###

GET http://localhost:5050/any-test

##

###
POST http://localhost:5050/any-test HTTP/1.1
content-type: application/plain

horse radish

###


### Query Parser: ([\w\d_-]+)(=)?(([\w\d_-]|(&(?:[\w\d_-]){1,5};)|([\w\d_-]+)))+
